#!/bin/bash

touch documentation

echo -e "Including the following files:\n"
for e in {"\.h","\.ih","\.cc"}
do
  array=($(find | grep $e | awk '{print substr($1,3)}' | sort))
  for i in "${array[@]}"
  do
    echo "$i"
    echo "\underline{$i}" >> documentation     ##
    echo "\begin{verbatim}" >> documentation   ##
    cat "$i" >> documentation
    echo "\end{verbatim}" >> documentation     ##
    echo -e "\n" >> documentation              ##
  done
done

# Lines marked with ## are echo statements that ensure that the produced output
# is valid LaTeX syntax.
